### ISSUE TITLE
[Bug]: It does not return tool_use information after send request for tool use

### ISSUE THREAD

**Issue by cavid90** [mozex/anthropic-laravel#4]
### Description

When I want use tool I send 'tools' parameter. It should return (probably api returns it) something like this:

`{
      "type": "tool_use",
      "id": "toolu_01A09q90qw90lq917835lq9",
      "name": "get_weather",
      "input": {"location": "San Francisco, CA"}
    }`

### Steps To Reproduce

Just send request with 'tools' parameter and see response. Detailed information is here: [Anthropic tool use](https://docs.anthropic.com/en/docs/build-with-claude/tool-use#json-mode)

### Anthropic Laravel Version

v1.0.1

### PHP Version

8.2

**Comment by cavid90** [comment]
You need to change CreateResponse so that it also converts tool_use type messages and returns input parameters

**Comment by mozex** [comment]
There is no support for using the tools currently because, until recently, they were in the beta version. I plan to work on this next week and will add the documentation as well, so keep checking the repository for changes.

**Comment by cavid90** [comment]
@mozex great, thanks a lot

**Comment by wassim** [comment]
@mozex any eta for this?

**Comment by cavid90** [comment]
Hello. I had to implement it myself. I can give you code so that you can use it on your side. 1st you need to have an api class for anthropic. Take into attention that I have not done refactoring yet. But the code works.

`public function __construct()
    {
        $this->client = Http::baseUrl(config('anthropic.url'))
            ->withHeaders([
            'X-API-KEY' => config('anthropic.api_key'),
            'ANTHROPIC-VERSION' => config('anthropic.version'),
            'Content-Type' => 'application/json'
        ])->timeout(config('anthropic.request_timeout'));
    }

    /**
     * Streamed messages with anthropic
     * @param $body
     * @return mixed
     */
    public function streamedMessages($body): mixed
    {
        try {
            $response = $this->client->post('messages', $body);
            $body = $response->toPsrResponse()->getBody();
            $stream = new StreamedResponse();
            $parts = [];
            $stream->setCallback(function () use ($body, &$parts) {
                while (!$body->eof()) {
                    $line = $this->readLine($body);

                    
                    if (! str_starts_with($line, 'data:') && ! str_starts_with($line, '{')) {
                        continue;
                    }

                    if(str_starts_with($line, '{')) {
                        $response = json_decode($line, true, flags: JSON_THROW_ON_ERROR);

                    } else {
                        $data = trim(substr($line, strlen('data:')));

                        /** @var array{type: string, error?: array{type: ?string, message: string|array<int, string>}} $response */
                        $response = json_decode($data, true, flags: JSON_THROW_ON_ERROR);

                    }

                    if (isset($response['error'])) {
                        throw new ErrorException($response['error']);
                    }

                    if ($response['type'] === 'message_stop') {
                        break;
                    }

                    $parts[] = $response;
                }
            })->sendContent();

            $contentType = $response->header('Content-Type');
            $stream->headers->set('Content-Type', $contentType);

            return ['body' => $parts, 'headers' => $response->headers()];
        } catch (\Exception $e) {
            Log::error($e);
            return false;
        }
    }

    private function readLine(StreamInterface $stream): string
    {
        $buffer = '';

        while (! $stream->eof()) {
            if ('' === ($byte = $stream->read(1))) {
                return $buffer;
            }
            $buffer .= $byte;
            if ($byte === "\n") {
                break;
            }
        }

        return $buffer;
    }`


Then you need to have a service which will convert the streamed message into format you need:

`/**
     * Get and convert streamed messages
     * @param $body
     * @return CreateMessage
     */
    public static function messagesStreamed($body): CreateMessage
    {
        $class = new self();
        try {
            $response = $class->api->streamedMessages($body);
            $usage = [
                'input_tokens' => 0,
                'output_tokens' => 0,
            ];

            $message = [
                'id' => '',
                'model' => '',
                'type' => '',
                'role' => '',
                'content' => [],
                'stop_reason' => '',
            ];

            if(count($response['body']) == 0) {
                return $class->convertMessage(false);
            }
            foreach ($response['body'] as $a) {

                if($a['type'] == 'message_start') {
                    $message['id'] = $a['message']['id'];
                    $message['model'] = $a['message']['model'];
                    $message['type'] = $a['message']['type'];
                    $message['role'] = $a['message']['role'];

                    $usage['input_tokens'] = $a['message']['usage']['input_tokens'];
                } elseif($a['type'] == 'message_delta') {
                    $usage['output_tokens'] = $a['usage']['output_tokens'];
                    $message['stop_reason'] = $a['delta']['stop_reason'];
                    $message['stop_sequence'] = $a['delta']['stop_sequence'];
                } elseif ($a['type'] == 'content_block_start') {
                    $index = $a['index'];
                    if(empty($message['content'][$index])) {

                        if($a['content_block']['type'] == 'text') {
                            $message['content'][$index] = [
                                'type' => 'text',
                                'text' => '',
                            ];
                        } else {
                            $message['content'][$index] = [
                                'type' => 'tool_use',
                                'id' => $a['content_block']['id'],
                                'name' => $a['content_block']['name'],
                                'input' => $a['content_block']['input'],
                                'partial_json' => ''
                            ];
                        }
                    }
                } elseif($a['type'] == 'content_block_delta') {
                    $index = $a['index'];
                    if($a['delta']['type'] == 'text_delta') { // is text
                        $message['content'][$index]['text'] .= $a['delta']['text'];
                    } else {
                        $message['content'][$index]['partial_json'] .= $a['delta']['partial_json'];
                    }

                } else {
                    // if this is error or message (usually tool message)
                    if($a['type'] == 'error' || $a['type'] == 'message') {
                        $message = $a;
                        $usage = [
                            'input_tokens' => $a['usage']['input_tokens'],
                            'output_tokens' => $a['usage']['output_tokens']
                        ];
                        $message['usage'] = (object) $usage;
                        break;
                    }
                }

            }

            $contents = [];
            foreach ($message['content'] as $content) {
                if($content['type'] == 'tool_use') {
                    if(array_key_exists('partial_json', $content)) {
                        $decodedInput = json_decode($content['partial_json']);
                        $content['input'] = (object)$decodedInput;
                        unset($content['partial_json']);
                    } else {
                        $content['input'] = (object)$content['input'];
                    }

                }
                $contents[] = (object)$content;
            }

            $message['content'] = $contents;
            $message['usage'] = (object)$usage;`

**Comment by cavid90** [comment]
I did not add code for CreateMessage class. because I convert the results into chatgpt message format. You may not need it.

**Comment by wassim** [comment]
@mozex can you reopen this please?

**Comment by connecteev** [comment]
@mozex any plans to integrate this?

**Comment by mozex** [comment]
I do plan on adding it but i have been a little busy lately, i will try to implement it next week.
In the mean time any PR will be appreciated.

**Comment by mozex** [comment]
Tool use support has been added to the [1.1.0](https://github.com/mozex/anthropic-php/releases/tag/1.1.0) version. Please update your dependencies and let me know if you have any issues.
